M48
; DRILL file {KiCad 8.0.3} date 2025-11-12T17:38:54-0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-12T17:38:54-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.3
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.750
%
G90
G05
T1
X130.6Y-94.7
X141.5Y-113.1
T2
X138.8Y-89.05
X146.5Y-89.05
X154.0Y-89.015
M30
